# Generated by Django 4.1 on 2024-11-10 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя картинки')),
                ('sorting', models.PositiveIntegerField(default=0)),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка')),
            ],
            options={
                'ordering': ['sorting'],
            },
        ),
    ]
